#resources:
#  - name: gated_docker_webhook
#    type: IncomingWebhook
#    configuration:
#      webhookName: gated_docker

pipelines:
  - name: Create_Release_Bundle
#    configuration:
#      environmentVariables:
#        readOnly:
#          local_repo_name: scanned-docker-local
#          remote_repo_name: dockerhub-docker-remote
    steps:
    - name: ExampleStep
      type: Bash
      configuration:
        integrations:
          - name: artifactory
        inputResources:
#          - name: gated_docker_webhook
          - name: danielw_gitrepo
            trigger: false
      execution:
          onExecute:
            - python3 --version
            - ls -lR
            - cp ./dependencyState/resources/danielw_gitrepo/create_release_bundle.py .
            - python3 create_release_bundle.py
