pipelines:
  - name: Create_Release_Bundle
    steps:
    - name: ExampleStep
      type: Bash
      configuration:
        integrations:
          - name: distribution
        inputResources:
          - name: danielw_gitrepo
            trigger: false
      execution:
          onExecute:
            - python3 --version
            - ls -lR
            - cp ./dependencyState/resources/danielw_gitrepo/create_release_bundle.py .
            - python3 create_release_bundle.py
